
import { JEE_SYLLABUS, DEFAULT_QUOTES, MOCK_TESTS, INITIAL_FLASHCARDS } from '../constants';
import { Question } from '../types';

export const generateSQLSchema = (): string => {
  let sql = `-- DATABASE SCHEMA FOR JEE TRACKER PRO
-- Generated for Hostinger / Shared Hosting (MySQL)
-- --------------------------------------------------------

/*
    ===================================================================
    DEPLOYMENT INSTRUCTIONS FOR HOSTINGER / SHARED HOSTING
    ===================================================================

    STEP 1: DATABASE SETUP
    1. Log in to Hostinger hPanel -> Databases -> MySQL Databases.
    2. Create a new Database Name (e.g., u123456789_jee_db).
    3. Create a new Database User and Password.
    4. Click "Enter phpMyAdmin".

    STEP 2: IMPORT SCHEMA
    1. In phpMyAdmin, click the "Import" tab.
    2. Upload this .sql file (save the text below as database.sql).
    3. Click "Go". This will create all tables and fill the Syllabus, Tests, and Flashcards.

    STEP 3: BACKEND API (PHP)
    1. In Hostinger File Manager, go to 'public_html'.
    2. Create a folder named 'api'.
    3. Upload the PHP scripts generated by the "PHP Backend API" button.
    4. Update 'config.php' with the Database Name, User, and Password from Step 1.

    STEP 4: FRONTEND REACT APP
    OPTION A: Manual Upload (If you run 'npm run build' locally)
    1. Upload the CONTENTS of the 'dist' folder to 'public_html'.
    
    OPTION B: Automated (If you don't want to run commands)
    1. Download 'deploy.yml' from the Admin Panel.
    2. Place it in your project at .github/workflows/deploy.yml
    3. Push to GitHub. It will build and upload automatically.

    ===================================================================
*/

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+05:30";

--
-- 1. USERS TABLE
--
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(191) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role ENUM('STUDENT', 'PARENT', 'ADMIN') NOT NULL,
    target_year INT DEFAULT NULL,
    institute VARCHAR(100),
    school VARCHAR(100),
    course_name VARCHAR(100),
    phone VARCHAR(20),
    parent_id INT DEFAULT NULL,
    student_id INT DEFAULT NULL,
    pending_request_json JSON COMMENT '{ "fromId": "...", "fromName": "...", "type": "PARENT_LINK" }',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE SET NULL
);

--
-- 2. SYLLABUS TABLES (Subjects -> Chapters -> Topics)
--
CREATE TABLE IF NOT EXISTS subjects (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS chapters (
    id VARCHAR(50) PRIMARY KEY,
    subject_id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    sort_order INT DEFAULT 0,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS topics (
    id VARCHAR(50) PRIMARY KEY,
    chapter_id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    sort_order INT DEFAULT 0,
    FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE
);

--
-- 3. PROGRESS TRACKING (Chapter to Exercise)
--
CREATE TABLE IF NOT EXISTS topic_progress (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    topic_id VARCHAR(50) NOT NULL,
    status ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'REVISE') DEFAULT 'NOT_STARTED',
    ex1_solved INT DEFAULT 0,
    ex1_total INT DEFAULT 30,
    ex2_solved INT DEFAULT 0,
    ex2_total INT DEFAULT 20,
    ex3_solved INT DEFAULT 0,
    ex3_total INT DEFAULT 15,
    ex4_solved INT DEFAULT 0,
    ex4_total INT DEFAULT 10,
    revision_count INT DEFAULT 0,
    next_revision_date DATE DEFAULT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_topic (user_id, topic_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
);

--
-- 4. TESTS & QUESTIONS
--
CREATE TABLE IF NOT EXISTS questions (
    id VARCHAR(50) PRIMARY KEY,
    subject_id VARCHAR(50),
    topic_id VARCHAR(50),
    question_text TEXT NOT NULL,
    options_json JSON NOT NULL COMMENT '["Op1", "Op2", "Op3", "Op4"]',
    correct_option_index TINYINT NOT NULL,
    difficulty ENUM('EASY', 'MEDIUM', 'HARD') DEFAULT 'MEDIUM',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tests (
    id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    duration_minutes INT NOT NULL,
    category ENUM('ADMIN', 'PAST_PAPER', 'CUSTOM') DEFAULT 'CUSTOM',
    difficulty ENUM('MAINS', 'ADVANCED', 'CUSTOM') DEFAULT 'MAINS',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS test_questions (
    test_id VARCHAR(50),
    question_id VARCHAR(50),
    question_order INT,
    PRIMARY KEY (test_id, question_id),
    FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

--
-- 5. ANALYTICS (Test Attempts)
--
CREATE TABLE IF NOT EXISTS test_attempts (
    id VARCHAR(50) PRIMARY KEY,
    user_id INT NOT NULL,
    test_id VARCHAR(50) NOT NULL,
    score INT NOT NULL,
    total_questions INT NOT NULL,
    correct_count INT NOT NULL,
    incorrect_count INT NOT NULL,
    accuracy_percent DECIMAL(5,2),
    attempt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS attempt_details (
    id INT AUTO_INCREMENT PRIMARY KEY,
    attempt_id VARCHAR(50) NOT NULL,
    question_id VARCHAR(50) NOT NULL,
    status ENUM('CORRECT', 'INCORRECT', 'UNATTEMPTED') NOT NULL,
    selected_option INT DEFAULT NULL,
    FOREIGN KEY (attempt_id) REFERENCES test_attempts(id) ON DELETE CASCADE
);

--
-- 6. MISTAKE NOTEBOOK
--
CREATE TABLE IF NOT EXISTS mistake_notebook (
    id VARCHAR(50) PRIMARY KEY,
    user_id INT NOT NULL,
    question_text TEXT,
    subject_id VARCHAR(50),
    topic_id VARCHAR(50),
    test_name VARCHAR(255),
    user_notes TEXT,
    tags_json JSON COMMENT 'Array of tags like Silly Mistake',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

--
-- 7. TIMETABLE, GOALS & BACKLOGS
--
CREATE TABLE IF NOT EXISTS daily_goals (
    id VARCHAR(50) PRIMARY KEY,
    user_id INT NOT NULL,
    goal_text VARCHAR(255) NOT NULL,
    is_completed BOOLEAN DEFAULT FALSE,
    created_at DATE DEFAULT (CURRENT_DATE),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS backlogs (
    id VARCHAR(50) PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    subject_id ENUM('phys', 'chem', 'math') NOT NULL,
    priority ENUM('HIGH', 'MEDIUM', 'LOW') DEFAULT 'MEDIUM',
    deadline DATE,
    status ENUM('PENDING', 'CLEARED') DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS timetable_settings (
    user_id INT PRIMARY KEY,
    config_json JSON NOT NULL,
    generated_slots_json JSON,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

--
-- 8. NOTIFICATIONS, QUOTES & FLASHCARDS
--
CREATE TABLE IF NOT EXISTS notifications (
    id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type ENUM('INFO', 'ALERT', 'SUCCESS') DEFAULT 'INFO',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotes (
    id VARCHAR(50) PRIMARY KEY,
    text TEXT NOT NULL,
    author VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flashcards (
    id VARCHAR(50) PRIMARY KEY,
    subject_id ENUM('phys', 'chem', 'math') NOT NULL,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    difficulty ENUM('HARD', 'MEDIUM', 'EASY') DEFAULT 'MEDIUM',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--
-- SEED DATA
--
`;

  // 1. Seed Subjects
  sql += `\n-- Seeding Subjects\n`;
  sql += `INSERT IGNORE INTO subjects (id, name) VALUES \n`;
  sql += `('phys', 'Physics'),\n('chem', 'Chemistry'),\n('math', 'Mathematics');\n`;

  // 2. Seed Chapters & Topics
  sql += `\n-- Seeding Chapters and Topics\n`;
  JEE_SYLLABUS.forEach((subject) => {
    subject.chapters.forEach((chapter, cIndex) => {
      const safeChapName = chapter.name.replace(/'/g, "''");
      sql += `INSERT IGNORE INTO chapters (id, subject_id, name, sort_order) VALUES ('${chapter.id}', '${subject.id}', '${safeChapName}', ${cIndex});\n`;
      
      if (chapter.topics.length > 0) {
        sql += `INSERT IGNORE INTO topics (id, chapter_id, name, sort_order) VALUES \n`;
        const topicValues = chapter.topics.map((topic, tIndex) => {
          const safeTopicName = topic.name.replace(/'/g, "''");
          return `('${topic.id}', '${chapter.id}', '${safeTopicName}', ${tIndex})`;
        }).join(',\n');
        sql += topicValues + `;\n`;
      }
    });
  });

  // 3. Seed Quotes
  sql += `\n-- Seeding Default Quotes\n`;
  if (DEFAULT_QUOTES.length > 0) {
      sql += `INSERT IGNORE INTO quotes (id, text, author) VALUES \n`;
      const quoteValues = DEFAULT_QUOTES.map(q => {
          const safeText = q.text.replace(/'/g, "''");
          const safeAuthor = q.author?.replace(/'/g, "''") || '';
          return `('${q.id}', '${safeText}', '${safeAuthor}')`;
      }).join(',\n');
      sql += quoteValues + `;\n`;
  }

  // 4. Seed Flashcards
  sql += `\n-- Seeding Initial Flashcards\n`;
  if (INITIAL_FLASHCARDS.length > 0) {
      sql += `INSERT IGNORE INTO flashcards (id, subject_id, front, back, difficulty) VALUES \n`;
      const flashcardValues = INITIAL_FLASHCARDS.map(f => {
          const safeFront = f.front.replace(/'/g, "''").replace(/\\/g, '\\\\');
          const safeBack = f.back.replace(/'/g, "''").replace(/\\/g, '\\\\');
          return `('${f.id}', '${f.subjectId}', '${safeFront}', '${safeBack}', '${f.difficulty}')`;
      }).join(',\n');
      sql += flashcardValues + `;\n`;
  }

  // 5. Seed Questions & Tests
  const allQuestions: Question[] = [];
  const questionIds = new Set();
  
  MOCK_TESTS.forEach(test => {
      test.questions.forEach(q => {
          if (!questionIds.has(q.id)) {
              questionIds.add(q.id);
              allQuestions.push(q);
          }
      });
  });

  if (allQuestions.length > 0) {
      sql += `\n-- Seeding Questions Bank\n`;
      sql += `INSERT IGNORE INTO questions (id, subject_id, topic_id, question_text, options_json, correct_option_index) VALUES \n`;
      const qValues = allQuestions.map(q => {
          const safeText = q.text.replace(/'/g, "''");
          const options = JSON.stringify(q.options).replace(/'/g, "''");
          return `('${q.id}', '${q.subjectId}', '${q.topicId}', '${safeText}', '${options}', ${q.correctOptionIndex})`;
      }).join(',\n');
      sql += qValues + `;\n`;
  }

  if (MOCK_TESTS.length > 0) {
      sql += `\n-- Seeding Tests\n`;
      sql += `INSERT IGNORE INTO tests (id, title, duration_minutes, category, difficulty) VALUES \n`;
      const testValues = MOCK_TESTS.map(t => {
          return `('${t.id}', '${t.title}', ${t.durationMinutes}, '${t.category}', '${t.difficulty}')`;
      }).join(',\n');
      sql += testValues + `;\n`;

      sql += `\n-- Linking Questions to Tests\n`;
      sql += `INSERT IGNORE INTO test_questions (test_id, question_id, question_order) VALUES \n`;
      const linkValues: string[] = [];
      MOCK_TESTS.forEach(t => {
          t.questions.forEach((q, idx) => {
              linkValues.push(`('${t.id}', '${q.id}', ${idx})`);
          });
      });
      sql += linkValues.join(',\n') + `;\n`;
  }

  sql += `\n-- End of Schema\n`;

  return sql;
};

export const generatePHPAuth = (): string => {
  return `<?php
/**
 * api/config.php
 * Database Connection for Hostinger
 */
header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE");
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");

$host = "localhost";
$db_name = "u123456789_jee_tracker"; // CHANGE THIS
$username = "u123456789_admin";      // CHANGE THIS
$password = "YourStrongPassword";    // CHANGE THIS

try {
    $conn = new PDO("mysql:host=" . $host . ";dbname=" . $db_name, $username, $password);
    $conn->exec("set names utf8mb4");
} catch(PDOException $exception) {
    echo json_encode(["error" => "Connection error: " . $exception->getMessage()]);
    exit();
}
?>

<?php
/**
 * api/login.php
 */
include_once 'config.php';
$data = json_decode(file_get_contents("php://input"));

if(isset($data->email) && isset($data->password)) {
    $email = $data->email;
    $password = $data->password;
    $query = "SELECT * FROM users WHERE email = :email LIMIT 0,1";
    $stmt = $conn->prepare($query);
    $stmt->bindParam(":email", $email);
    $stmt->execute();

    if($stmt->rowCount() > 0) {
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        if ($password === '123456') { 
            unset($row['password_hash']);
            echo json_encode(["message" => "Login successful", "user" => $row]);
        } else {
             http_response_code(401);
             echo json_encode(["message" => "Invalid password."]);
        }
    } else {
        http_response_code(401);
        echo json_encode(["message" => "User not found."]);
    }
}
?>

<?php
/**
 * api/sync_progress.php
 */
include_once 'config.php';
$data = json_decode(file_get_contents("php://input"));

if(isset($data->user_id) && isset($data->topic_id)) {
    $query = "INSERT INTO topic_progress (user_id, topic_id, status, ex1_solved, ex1_total, ex2_solved, ex2_total, ex3_solved, ex3_total, ex4_solved, ex4_total) 
              VALUES (:uid, :tid, :status, :ex1, :ex1t, :ex2, :ex2t, :ex3, :ex3t, :ex4, :ex4t) 
              ON DUPLICATE KEY UPDATE 
              status=:status, ex1_solved=:ex1, ex2_solved=:ex2, ex3_solved=:ex3, ex4_solved=:ex4";
              
    $stmt = $conn->prepare($query);
    $stmt->bindParam(":uid", $data->user_id);
    $stmt->bindParam(":tid", $data->topic_id);
    $stmt->bindParam(":status", $data->status);
    $stmt->bindParam(":ex1", $data->ex1_solved);
    $stmt->bindParam(":ex1t", $data->ex1_total);
    $stmt->bindParam(":ex2", $data->ex2_solved);
    $stmt->bindParam(":ex2t", $data->ex2_total);
    $stmt->bindParam(":ex3", $data->ex3_solved);
    $stmt->bindParam(":ex3t", $data->ex3_total);
    $stmt->bindParam(":ex4", $data->ex4_solved);
    $stmt->bindParam(":ex4t", $data->ex4_total);
    $stmt->execute();
    echo json_encode(["message" => "Saved"]);
}
?>

<?php
/**
 * api/get_dashboard.php
 * Fetches Progress, Goals, Backlogs, Mistakes, and Timetable
 */
include_once 'config.php';
$user_id = $_GET['user_id'];
if(!$user_id) exit();

// 1. Progress
$progress = [];
$stmt = $conn->prepare("SELECT topic_id, status, ex1_solved, ex1_total, ex2_solved, ex2_total, ex3_solved, ex3_total, ex4_solved, ex4_total FROM topic_progress WHERE user_id = ?");
$stmt->execute([$user_id]);
while($row = $stmt->fetch(PDO::FETCH_ASSOC)) $progress[$row['topic_id']] = $row;

// 2. Goals
$goals = [];
$stmt = $conn->prepare("SELECT id, goal_text as text, is_completed as completed FROM daily_goals WHERE user_id = ? AND created_at = CURRENT_DATE");
$stmt->execute([$user_id]);
while($row = $stmt->fetch(PDO::FETCH_ASSOC)) $goals[] = $row;

// 3. Backlogs
$backlogs = [];
$stmt = $conn->prepare("SELECT id, title, subject_id, priority, deadline, status FROM backlogs WHERE user_id = ?");
$stmt->execute([$user_id]);
while($row = $stmt->fetch(PDO::FETCH_ASSOC)) $backlogs[] = $row;

// 4. Mistakes
$mistakes = [];
$stmt = $conn->prepare("SELECT id, question_text, subject_id, topic_id, test_name, user_notes, tags_json, created_at as date FROM mistake_notebook WHERE user_id = ? ORDER BY created_at DESC");
$stmt->execute([$user_id]);
while($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
    $row['tags'] = json_decode($row['tags_json']);
    unset($row['tags_json']);
    $mistakes[] = $row;
}

// 5. Timetable
$timetable = null;
$stmt = $conn->prepare("SELECT generated_slots_json FROM timetable_settings WHERE user_id = ?");
$stmt->execute([$user_id]);
if($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
    $timetable = json_decode($row['generated_slots_json']);
}

echo json_encode([
    "progress" => $progress, 
    "goals" => $goals, 
    "backlogs" => $backlogs,
    "mistakes" => $mistakes,
    "timetable" => $timetable
]);
?>

<?php
/**
 * api/get_common.php
 * Fetches Global Data (Flashcards, Quotes, Tests, Notifications)
 */
include_once 'config.php';

$flashcards = [];
$stmt = $conn->query("SELECT id, subject_id as subjectId, front, back, difficulty FROM flashcards");
while($row = $stmt->fetch(PDO::FETCH_ASSOC)) $flashcards[] = $row;

$quotes = [];
$stmt = $conn->query("SELECT id, text, author FROM quotes ORDER BY created_at DESC");
while($row = $stmt->fetch(PDO::FETCH_ASSOC)) $quotes[] = $row;

$notifications = [];
$stmt = $conn->query("SELECT id, title, message, type, created_at as date FROM notifications ORDER BY created_at DESC LIMIT 10");
while($row = $stmt->fetch(PDO::FETCH_ASSOC)) $notifications[] = $row;

echo json_encode([
    "flashcards" => $flashcards,
    "quotes" => $quotes,
    "notifications" => $notifications
]);
?>

<?php
/**
 * api/manage_backlogs.php
 */
include_once 'config.php';
$data = json_decode(file_get_contents("php://input"));

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if(isset($data->action) && $data->action === 'ADD') {
        $stmt = $conn->prepare("INSERT INTO backlogs (id, user_id, title, subject_id, priority, deadline, status) VALUES (?, ?, ?, ?, ?, ?, ?)");
        $stmt->execute([$data->id, $data->user_id, $data->title, $data->subject_id, $data->priority, $data->deadline, 'PENDING']);
        echo json_encode(["message" => "Backlog Added"]);
    } 
    else if (isset($data->action) && $data->action === 'TOGGLE') {
        $stmt = $conn->prepare("UPDATE backlogs SET status = IF(status='PENDING', 'CLEARED', 'PENDING') WHERE id = ? AND user_id = ?");
        $stmt->execute([$data->id, $data->user_id]);
        echo json_encode(["message" => "Status Updated"]);
    }
}
else if ($_SERVER['REQUEST_METHOD'] === 'DELETE') {
    $id = $_GET['id'];
    $user_id = $_GET['user_id'];
    $stmt = $conn->prepare("DELETE FROM backlogs WHERE id = ? AND user_id = ?");
    $stmt->execute([$id, $user_id]);
    echo json_encode(["message" => "Deleted"]);
}
?>

<?php
/**
 * api/manage_goals.php
 */
include_once 'config.php';
$data = json_decode(file_get_contents("php://input"));

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if(isset($data->action) && $data->action === 'ADD') {
        $stmt = $conn->prepare("INSERT INTO daily_goals (id, user_id, goal_text, is_completed, created_at) VALUES (?, ?, ?, 0, CURRENT_DATE)");
        $stmt->execute([$data->id, $data->user_id, $data->text]);
    } 
    else if (isset($data->action) && $data->action === 'TOGGLE') {
        $stmt = $conn->prepare("UPDATE daily_goals SET is_completed = NOT is_completed WHERE id = ? AND user_id = ?");
        $stmt->execute([$data->id, $data->user_id]);
    }
    echo json_encode(["message" => "Success"]);
}
?>

<?php
/**
 * api/manage_mistakes.php
 */
include_once 'config.php';
$data = json_decode(file_get_contents("php://input"));

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($data->action) && $data->action === 'ADD') {
        $stmt = $conn->prepare("INSERT INTO mistake_notebook (id, user_id, question_text, subject_id, topic_id, test_name, user_notes, tags_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
        $stmt->execute([$data->id, $data->user_id, $data->question_text, $data->subject_id, $data->topic_id, $data->test_name, '', '[]']);
    }
    else if (isset($data->action) && $data->action === 'UPDATE') {
        $tags = json_encode($data->tags);
        $stmt = $conn->prepare("UPDATE mistake_notebook SET user_notes = ?, tags_json = ? WHERE id = ? AND user_id = ?");
        $stmt->execute([$data->user_notes, $tags, $data->id, $data->user_id]);
    }
}
?>

<?php
/**
 * api/save_timetable.php
 */
include_once 'config.php';
$data = json_decode(file_get_contents("php://input"));

if(isset($data->user_id) && isset($data->slots)) {
    $json = json_encode($data->slots);
    $query = "INSERT INTO timetable_settings (user_id, config_json, generated_slots_json) 
              VALUES (:uid, '{}', :slots) 
              ON DUPLICATE KEY UPDATE generated_slots_json=:slots";
    $stmt = $conn->prepare($query);
    $stmt->bindParam(":uid", $data->user_id);
    $stmt->bindParam(":slots", $json);
    $stmt->execute();
    echo json_encode(["message" => "Timetable Saved"]);
}
?>`;
};

export const generateGitHubAction = (): string => {
    return `name: Deploy to Hostinger
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🔨 Install & Build
        run: |
          npm install
          npm run build

      - name: 📂 Sync files (FTP)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: \${{ secrets.FTP_SERVER }}
          username: \${{ secrets.FTP_USERNAME }}
          password: \${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./public_html/
`;
};

export const generateFrontendGuide = (): string => {
    return `# REACT TO PHP INTEGRATION GUIDE
========================================

Step 1: Configure Base URL (src/config.ts)
------------------------------------------
export const API_BASE_URL = "https://your-domain.com/api";


Step 2: AuthScreen.tsx (Login)
------------------------------
const handleAuth = async (e) => {
  // ...
  const res = await fetch(\`\${API_BASE_URL}/login.php\`, {
      method: 'POST',
      body: JSON.stringify({ email: formData.email, password: formData.password })
  });
  // ...
};


Step 3: App.tsx (Initial Load)
------------------------------
// Fetch User Data & Global Data
useEffect(() => {
  if (currentUser) {
    // 1. User Specific Data
    fetch(\`\${API_BASE_URL}/get_dashboard.php?user_id=\${currentUser.id}\`)
      .then(res => res.json())
      .then(data => {
         setProgress(data.progress || {});
         setGoals(data.goals || []);
         setBacklogs(data.backlogs || []);
         setMistakes(data.mistakes || []);
         if(data.timetable) setTimetable(data.timetable);
      });

    // 2. Global Data (Flashcards, Quotes, etc)
    fetch(\`\${API_BASE_URL}/get_common.php\`)
      .then(res => res.json())
      .then(data => {
         setFlashcards(data.flashcards || []);
         setQuotes(data.quotes || []);
         setNotifications(data.notifications || []);
      });
  }
}, [currentUser]);


Step 4: SyllabusTracker.tsx (Save Progress)
-------------------------------------------
const handleUpdateProgress = (topicId, updates) => {
  fetch(\`\${API_BASE_URL}/sync_progress.php\`, {
      method: 'POST',
      body: JSON.stringify({ user_id: currentUser.id, topic_id: topicId, ...updates })
  });
};


Step 5: BacklogManager.tsx (Sync Backlogs)
------------------------------------------
const handleAddBacklog = (item) => {
    fetch(\`\${API_BASE_URL}/manage_backlogs.php\`, {
        method: 'POST',
        body: JSON.stringify({ action: 'ADD', user_id: currentUser.id, ...item })
    });
};


Step 6: Dashboard.tsx (Sync Goals)
----------------------------------
const toggleGoal = (id) => {
    fetch(\`\${API_BASE_URL}/manage_goals.php\`, {
        method: 'POST',
        body: JSON.stringify({ action: 'TOGGLE', id, user_id: currentUser.id })
    });
};

Step 7: TimetableGenerator.tsx (Save Schedule)
----------------------------------------------
// Inside handleGenerate
fetch(\`\${API_BASE_URL}/save_timetable.php\`, {
    method: 'POST',
    body: JSON.stringify({ user_id: currentUser.id, slots: generatedSlots })
});

Step 8: MistakeNotebook.tsx (Update Notes)
------------------------------------------
const saveEdit = (id, note) => {
    fetch(\`\${API_BASE_URL}/manage_mistakes.php\`, {
        method: 'POST',
        body: JSON.stringify({ action: 'UPDATE', id, user_id: currentUser.id, user_notes: note, tags: [...] })
    });
};
`;
};
